resId: ${context.res.id}
templates:
  cookie: |
    name: {{ .init.name }}
    port: {{ .init.port }}
    user: {{ .init.user }}
    password: {{ .init.password }}
    rootPassword: {{ .init.rootPassword }}
    database: {{ .init.database }}
  init: |-
    {{- if .cookie}}
    name: {{ .cookie.name }}
    port: {{ .cookie.port }}
    user: {{ .cookie.user }}
    password: {{ .cookie.password }}
    rootPassword: {{ .cookie.rootPassword }}
    database: {{ .cookie.database }}
    {{- else }}
    port: 3306
    user: {{ randAlpha 8 | lower | quote }}
    password: {{ randAlphaNum 16 | quote }}
    rootPassword: {{ randAlphaNum 16 | quote }}
    database: {{ randAlpha 8 | lower | quote }}
    # StatefulSets names are limited to 52 chars https://github.com/kubernetes/kubernetes/issues/64023
    {{ if regexMatch "modules\\.[a-z0-9-]+\\.externals" .driver.values.resId }}
    name: mysql-{{ index (splitList "." .driver.values.resId) 1 | substr 0 20 }}-{{ index (splitList "." .driver.values.resId) 3 | substr 0 20 }}
    {{- else }}
    name: mysql-{{ index (splitList "." .driver.values.resId) 1 | substr 0 40 }}
    {{- end }}
    {{- end }}
  manifests: |-
    statefulset.yaml:
      location: namespace
      data:
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: {{ .init.name }}
        spec:
          serviceName: mysql
          selector:
            matchLabels:
              app: {{ .init.name }}
          template:
            metadata:
              labels:
                app: {{ .init.name }}
            spec:
              containers:
                - name: {{ .init.name }}
                  image: mysql:8.0
                  env:
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: {{ .init.name }}
                          key: MYSQL_ROOT_PASSWORD
                    - name: MYSQL_DATABASE
                      value: {{ .init.database | quote }}
                    - name: MYSQL_USER
                      value: {{ .init.user | quote }}
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: {{ .init.name }}
                          key: MYSQL_PASSWORD
                  ports:
                    - containerPort: {{ .init.port }}
                      name: mysql
                  volumeMounts:
                    - name: {{ .init.name }}
                      mountPath: /var/lib/mysql
          volumeClaimTemplates:
            - metadata:
                name: {{ .init.name }}
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
    service.yaml:
      location: namespace
      data:
        apiVersion: v1
        kind: Service
        metadata:
          name: {{ .init.name }}
        spec:
          ports:
          - port: {{ .init.port }}
            targetPort: mysql
          selector:
            app: {{ .init.name }}
          clusterIP: None
    secret.yaml:
      location: namespace
      data:
        apiVersion: v1
        kind: Secret
        metadata:
          name: {{ .init.name }}
        type: Opaque
        data:
          MYSQL_ROOT_PASSWORD: {{ .init.rootPassword | b64enc }}
          MYSQL_PASSWORD: {{ .init.password | b64enc }}
  outputs: |-
    host: {{ .init.name }}
    port: {{ .init.port }}
    name: {{ .init.database }}
  secrets: |-
    username: {{ .init.user }}
    password: {{ .init.password }}